"""
Data loading functions for the example datasets.
"""
import os

import numpy as np

## get path of this file
file_path = os.path.dirname(os.path.abspath(__file__))

def ecoli100():
    """
    Load the 100 gene E. Coli dataset. This dataset was generated by greedily subsampling
    a connected component of the E. Coli regulon, and then simulated a stochastic
    kinetic model of gene expression dynamics.

    The data is stored in two files:
    - ecoli100genes0_adjmat.csv.gz: the adjacency matrix of the true causal graph
    - ecoli100genes0_X.csv.gz: the gene expression dynamics

    Returns:
        X: the gene expression dynamics, shape (n_timepoints, n_genes)
        amat: the adjacency matrix of the true causal graph, shape (n_genes, n_genes)
    
    """
    amat = np.loadtxt(file_path + "/data/ecoli100genes0_adjmat.csv.gz")
    X = np.loadtxt(file_path + "/data/ecoli100genes0_X.csv.gz")
    return X, amat

def ecoli10():
    """
    Load the 10 gene E. Coli dataset. This dataset was generated by greedily subsampling
    a connected component of the E. Coli regulon, and then simulated a stochastic
    kinetic model of gene expression dynamics.

    The data is stored in two files:
    - ecoli10genes0_adjmat.csv.gz: the adjacency matrix of the true causal graph
    - ecoli10genes0_X.csv.gz: the gene expression dynamics

    Returns:
        X: the gene expression dynamics, shape (n_timepoints, n_genes)
        amat: the adjacency matrix of the true causal graph, shape (n_genes, n_genes)
    """
    amat = np.loadtxt(file_path + "/data/ecoli10genes0_adjmat.csv.gz")
    X = np.loadtxt(file_path + "/data/ecoli10genes0_X.csv.gz")
    return X, amat


def yeast100():
    """
    Load the 100 gene yeast dataset. This dataset was generated by greedily subsampling
    a connected component of the yeast regulon, and then simulated a stochastic
    kinetic model of gene expression dynamics.
    """
    amat = np.loadtxt(file_path + "/data/yeast100genes0_adjmat.csv.gz")
    X = np.loadtxt(file_path + "/data/yeast100genes0_X.csv.gz")
    return X, amat

def ecoli100():
    """
    Load the 100 gene E. Coli dataset. This dataset was generated by greedily subsampling
    a connected component of the E. Coli regulon, and then simulated a stochastic
    kinetic model of gene expression dynamics.
    """
    amat = np.loadtxt(file_path + "/data/ecoli100genes0_adjmat.csv.gz")
    X = np.loadtxt(file_path + "/data/ecoli100genes0_X.csv.gz")
    return X, amat