[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rice"
version = "0.1"
description = "Discover causal relationships from time series"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "scikit-learn",
    "hnswlib",
]

# Optional dependencies
[project.optional-dependencies]
benchmarks = ["pandas", "tqdm", "yellowbrick @ git+https://github.com/DistrictDataLabs/yellowbrick.git@28d6fa4a54ed0a80f64ae75267b6f7e84c92e9e0", "requests", "regdiffusion"]
tests = ["matplotlib"]
scanpy = ["scanpy", "anndata", "seaborn>=0.13.2"]

# Package data
[tool.setuptools]
packages = ["rice"]

